config/routes.rb
Rails.application.routes.draw do

  root "categories#index"
  resources :categories
  get "articles/:id" => "articles#show"

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    # @article = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
    render :show, layout: false
    respond_to do |format|
      format.html { redirect_to votes_url }
      format.js { head :ok }
    end
  end

  def edit
    @category = Category.find(params[:id])

  end

  def update
    p params
    @category = Category.find(params[:id])
    if @category.update_attribute :category_name, params[:category][:category_name]
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to root_path
  end

  def new
    @categories = Category.new
    redirect_to root_path
  end


  def create
    @categories = Category.create( :category_name =>params[:category][:category_name])

    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<br>
<h5>email: <%= @article.email %></h5><h4>price: $<%= @article.price %></h4>
<p><%= @article.description %></p>



<a href="/categories/<%=@article.category.id %>"><%= @article.category.category_name %></a>

app/views/categories/edit.html.erb
<h1>Edit: <%= @category.category_name%></h1>


<%= form_for @category do |f|%>
  <ul>
    <li>
      <%= f.label :category_name %>
      <%= f.text_field :category_name %>
    </li>
    <li>
      <%= f.submit%>
    </li>
  </ul>

<% end%>

app/views/categories/index.html.erb
<div id="content">
<h1>Here are some categories</h1>

<ul>
<% @category.each do |category| %>
  <a data-id= "<%= category.id %>"class="category" href="/categories/<%=category.id%>"><li><%= category.category_name %></li></a>
<% end %>
</ul>



<h1>Create a new category</h1>

<ul>
  <% @categories = Category.new%>
  <%= form_for @categories do |f| %>
    <li>
      <%= f.label :category_name %>
      <%= f.text_field :category_name %>
    </li>
    <li>
      <%= f.submit %>
    </li>

<% end %>

</ul>
</div>

app/views/categories/show.html.erb
<h1><%= @category.category_name %></h1>

<% @category.articles.each do |article| %>
  <a href="/articles/<%= article.id %>"><div><%= article.title %>:</div></a>

  <div><%= article.description %></div>
  <br>
<% end %>

<a href="/">HOMEPAGE</a>

<!-- <a href="/categories/<%= @category.id %>/edit">edit your page</a>
 -->
<span><%= link_to "edit", edit_category_path(@category) %></span>

<span><%= link_to "delete", category_path(@category), :method => :delete %></span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>